import type { Puzzle } from "../types/puzzles";

const CODING_QUESTIONS: ReadonlyArray<{ q: string; a: string }> = [
  { q: "What does HTML stand for? (type: markup)", a: "markup" },
  { q: "What loop keyword continues to the next iteration in JS?", a: "continue" },
  { q: "What keyword declares a constant in JavaScript?", a: "const" },
  { q: "What does CSS stand for? (type: cascading)", a: "cascading" },
  { q: "What HTTP status code means 'Not Found'?", a: "404" },
  { q: "What HTTP status code means 'OK'?", a: "200" },
  { q: "What data structure uses LIFO (Last In First Out)?", a: "stack" },
  { q: "What data structure uses FIFO (First In First Out)?", a: "queue" },
  { q: "What is 2 to the power of 8?", a: "256" },
  { q: "How many bits in a byte?", a: "8" },
  { q: "What does SQL stand for? (type: structured)", a: "structured" },
  { q: "What is the result of true && false in JavaScript?", a: "false" },
  { q: "What keyword breaks out of a loop in most languages?", a: "break" },
  { q: "What is the index of the first element in an array?", a: "0" },
  { q: "What does API stand for? (type: application)", a: "application" },
  { q: "What does JSON stand for? (type: javascript)", a: "javascript" },
  { q: "What HTTP method is used to retrieve data?", a: "get" },
  { q: "What HTTP method is used to send data?", a: "post" },
  { q: "What HTTP method is used to update data?", a: "put" },
  { q: "What HTTP method is used to delete data?", a: "delete" },
  { q: "What HTTP status code means 'Unauthorized'?", a: "401" },
  { q: "What HTTP status code means 'Forbidden'?", a: "403" },
  { q: "What HTTP status code means 'Internal Server Error'?", a: "500" },
  { q: "What is the result of 10 % 3 in most languages?", a: "1" },
  { q: "What keyword is used to define a function in Python?", a: "def" },
  { q: "What symbol starts a comment in Python?", a: "#" },
  { q: "What symbol starts a single-line comment in JavaScript?", a: "//" },
  { q: "What does Git stand for? (type: git)", a: "git" },
  { q: "What command initializes a new Git repository?", a: "init" },
  { q: "What Git command shows the status of your repo?", a: "status" },
  { q: "What Git command stages changes?", a: "add" },
  { q: "What Git command saves your changes?", a: "commit" },
  { q: "What programming language runs in web browsers?", a: "javascript" },
  { q: "What is the most popular programming language in 2024?", a: "python" },
  { q: "What does OOP stand for? (type: object)", a: "object" },
  { q: "What is the opposite of synchronous?", a: "asynchronous" },
  { q: "What keyword is used for inheritance in many languages?", a: "extends" },
  { q: "What is null in JavaScript also known as?", a: "null" },
  { q: "What is the logical NOT operator in most languages?", a: "!" },
  { q: "What is the logical OR operator in JavaScript?", a: "||" },
  { q: "What is the logical AND operator in JavaScript?", a: "&&" },
  { q: "What does DOM stand for? (type: document)", a: "document" },
  { q: "What is 2^10 in computer science?", a: "1024" },
  { q: "How many bytes in a kilobyte?", a: "1024" },
  { q: "What is the extension for Python files?", a: ".py" },
  { q: "What is the extension for JavaScript files?", a: ".js" },
  { q: "What is the extension for TypeScript files?", a: ".ts" },
  { q: "What does CPU stand for? (type: central)", a: "central" },
  { q: "What does RAM stand for? (type: random)", a: "random" },
  { q: "What does URL stand for? (type: uniform)", a: "uniform" },
];

export function generateCodingPuzzle(): Puzzle {
  const selected = CODING_QUESTIONS[Math.floor(Math.random() * CODING_QUESTIONS.length)];
  return {
    question: selected.q,
    answer: selected.a,
    type: "coding",
  };
}
