import type { Puzzle } from "../types/puzzles";

const TRIVIA_QUESTIONS: ReadonlyArray<{ q: string; a: string }> = [
  { q: "How many days in a leap year?", a: "366" },
  { q: "How many continents are there?", a: "7" },
  { q: "What planet is known as the Red Planet?", a: "mars" },
  { q: "How many hours in a day?", a: "24" },
  { q: "How many minutes in an hour?", a: "60" },
  { q: "How many legs does a spider have?", a: "8" },
  { q: "What is the capital of France?", a: "paris" },
  { q: "What is the capital of Japan?", a: "tokyo" },
  { q: "How many sides does a triangle have?", a: "3" },
  { q: "What is the largest ocean on Earth?", a: "pacific" },
  { q: "How many seconds in a minute?", a: "60" },
  { q: "How many days in a regular year?", a: "365" },
  { q: "How many months in a year?", a: "12" },
  { q: "How many weeks in a year?", a: "52" },
  { q: "How many states are in the USA?", a: "50" },
  { q: "What is the capital of Italy?", a: "rome" },
  { q: "What is the capital of Germany?", a: "berlin" },
  { q: "What is the capital of Spain?", a: "madrid" },
  { q: "What is the capital of England?", a: "london" },
  { q: "What is the capital of Canada?", a: "ottawa" },
  { q: "What is the capital of Australia?", a: "canberra" },
  { q: "What is the capital of Russia?", a: "moscow" },
  { q: "What is the capital of China?", a: "beijing" },
  { q: "What is the capital of Brazil?", a: "brasilia" },
  { q: "What is the capital of Egypt?", a: "cairo" },
  { q: "What planet is closest to the Sun?", a: "mercury" },
  { q: "What is the largest planet in our solar system?", a: "jupiter" },
  { q: "What planet has rings?", a: "saturn" },
  { q: "What is Earth's only natural satellite?", a: "moon" },
  { q: "How many planets are in our solar system?", a: "8" },
  { q: "What is the smallest planet in our solar system?", a: "mercury" },
  { q: "What is the hottest planet in our solar system?", a: "venus" },
  { q: "How many sides does a square have?", a: "4" },
  { q: "How many sides does a pentagon have?", a: "5" },
  { q: "How many sides does a hexagon have?", a: "6" },
  { q: "How many sides does an octagon have?", a: "8" },
  { q: "How many degrees in a circle?", a: "360" },
  { q: "How many degrees in a right angle?", a: "90" },
  { q: "What is the speed of light? (type: 299792458)", a: "299792458" },
  { q: "What is the boiling point of water in Celsius?", a: "100" },
  { q: "What is the freezing point of water in Celsius?", a: "0" },
  { q: "How many teeth does an adult human have?", a: "32" },
  { q: "How many bones are in the human body?", a: "206" },
  { q: "What is the largest mammal on Earth?", a: "blue whale" },
  { q: "What is the fastest land animal?", a: "cheetah" },
  { q: "What is the tallest mountain in the world?", a: "everest" },
  { q: "What is the longest river in the world?", a: "nile" },
  { q: "What is the largest country by area?", a: "russia" },
  { q: "What is the most populated country?", a: "china" },
  { q: "What language is most spoken worldwide?", a: "english" },
  { q: "How many colors in a rainbow?", a: "7" },
  { q: "What is the smallest unit of life?", a: "cell" },
  { q: "What do bees make?", a: "honey" },
  { q: "What is the opposite of hot?", a: "cold" },
  { q: "What is the opposite of up?", a: "down" },
  { q: "What is the opposite of left?", a: "right" },
  { q: "How many players on a basketball team?", a: "5" },
  { q: "How many players on a soccer team?", a: "11" },
  { q: "How many strings on a standard guitar?", a: "6" },
  { q: "How many keys on a standard piano?", a: "88" },
];

export function generateTriviaPuzzle(): Puzzle {
  const selected = TRIVIA_QUESTIONS[Math.floor(Math.random() * TRIVIA_QUESTIONS.length)];
  return {
    question: selected.q,
    answer: selected.a,
    type: "trivia",
  };
}
